FROM node:12-alpine
WORKDIR /usr/node/app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY public/ ./public/
COPY src/ ./src/
COPY babel-plugin-macros.config.js tsconfig.json ./

EXPOSE 3000
CMD yarn run start
