version: "3.7"

volumes:
  database:
    external: true
    name: mongo-database

services:
  database:
    image: mongo
    volumes:
      - database:/data/db
    expose:
      - 27017

  server:
    image: grmiade/doowit-graphql
    environment:
      MONGO_URL: mongodb://database:27017/doowit
    depends_on:
      - database
    ports:
      - 4000:4000

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_GRAPHQL_URL: http://localhost:4000/graphql
      REACT_APP_GRAPHQL_WEBSOCKET: ws://localhost:4000/graphql
    depends_on:
      - server
    volumes:
      - ./src:/usr/node/app/src
    ports:
      - 3000:3000
